### ISSUE TITLE
FEEDBACK

### ISSUE THREAD

**Issue by LuckFire** [LuckFire/amoled-cord#20]
It appears there's a decent amount of people that dislike this update and prefer the old version. If you're one of these people, or not (I'll take any feedback from users), could you give me feedback on why you dislike / like the changes? What should be different and / or change?

**Comment by elijaholmos** [comment]
I'll give my two cents:
I strongly preferred the old theme because of the consistent dark across the platform. Some of the recent changes you made to v2 are a step in the right direction, and I especially like the gray background behind emojis now, but here's a few things that seem to be broken:

![image](https://user-images.githubusercontent.com/35435704/144064656-86050281-c040-4852-8ca8-0f624dc427e0.png)
Quick picker menu built into Discord (CTRL + K)

![image](https://user-images.githubusercontent.com/35435704/144064738-9b12c832-91d8-49cf-892c-54ab23e8d0b6.png)
A couple of plugins that add to the Discord app have been broken, I assume because of their use of default variables. The tabs on the top come from BetterDiscord ChannelTabs 2.5.6, and the member count on the right comes from BetterDiscord MemberCount 2.2.9

![image](https://user-images.githubusercontent.com/35435704/144065303-36ac9916-6553-4b51-b44b-9b6cbc2d71b0.png)

Some of the built-in BetterDiscord stuff seems to be using the default Discord gray as well

The BetterDiscord plugins are probably a little niche, but I know a lot of them build off the default CSS variables, so I'm not sure how you'd like to address that to handle future occurrences. Just giving some feedback :)

**Comment by amxmu** [comment]
> I'll give my two cents: I strongly preferred the old theme because of the consistent dark across the platform. Some of the recent changes you made to v2 are a step in the right direction, and I especially like the gray background behind emojis now, but here's a few things that seem to be broken:
> 
> ![image](https://user-images.githubusercontent.com/35435704/144064656-86050281-c040-4852-8ca8-0f624dc427e0.png) Quick picker menu built into Discord (CTRL + K)
> 
> ![image](https://user-images.githubusercontent.com/35435704/144064738-9b12c832-91d8-49cf-892c-54ab23e8d0b6.png) A couple of plugins that add to the Discord app have been broken, I assume because of their use of default variables. The tabs on the top come from BetterDiscord ChannelTabs 2.5.6, and the member count on the right comes from BetterDiscord MemberCount 2.2.9
> 
> ![image](https://user-images.githubusercontent.com/35435704/144065303-36ac9916-6553-4b51-b44b-9b6cbc2d71b0.png)
> 
> Some of the built-in BetterDiscord stuff seems to be using the default Discord gray as well
> 
> The BetterDiscord plugins are probably a little niche, but I know a lot of them build off the default CSS variables, so I'm not sure how you'd like to address that to handle future occurrences. Just giving some feedback :)

+1 on this -- I was going to make a post myself about some of the unthemed sections, and I put in the original code from here into the theme file on BetterDiscord so I could darken some parts to how dark they were in 1.0 but thats just my personal preference. Apart from the unthemed sections, it was overall pretty good update.

**Comment by LuckFire** [comment]
thank you for the feedback, ill also make sure to theme the things i've missed (so if you notice more, let me know)

if you notice any other particular plugin that needs an area themed, let me know.

**Comment by elijaholmos** [comment]
this is looking a lot better @LuckFire, thanks for the changes 🙂

**Comment by LuckFire** [comment]
glad to her that

**Comment by LaeMat** [comment]
Stylus style just doesn't work at all, even after refreshing or reopening Firefox.

**Comment by amxmu** [comment]
> thank you for the feedback, ill also make sure to theme the things i've missed (so if you notice more, let me know)
> 
> if you notice any other particular plugin that needs an area themed, let me know as well.

The window to choose "which window to stream" where you can click applications/share screen is also unthemed.

**Comment by etherb0x** [comment]
Hey there! Just noticed that the Stages background is back to the Discord standard grey gradient—any tips on how to override that to go back to pure black? Or else skin it otherwise? Not familiar with which element I'd need to change in the CSS editor.

I was enjoying this theme for saving wear and tear on my OLED + being able to easily color key away the backdrop in OBS for a weekly Stages podcast I record; with the grey gradient, this isn't cleanly possible.

**Comment by TheHunter1234** [comment]
Change connections to this, please. I like that you added color to it but I would like a border, not the entire thing filled in. I don't know if others agree or not but I( think it would look better. Also with rounded corners too.

`/*profile connection borders*/
.connectedAccountIcon-3_EQqg ~ div::before {
  content: "";
  top: 0; bottom: 0; left: 0; right: 0;
  border: 1px solid var(--border-color);
  position: absolute;
  display: block;
  pointer-events: none;
}

.connectedAccount-2Jb-Z0{
  overflow: hidden;
  position: relative;
}
/* Spotify */
.connectedAccountIcon-3_EQqg[src="/assets/eaeac24163b35f7526704a3d9b3c7722.svg"] ~ div::before {--border-color: #1ED760;}
/* Github */
.connectedAccountIcon-3_EQqg[src="/assets/6a853b4c87fce386cbfef4a2efbacb09.svg"] ~ div::before {--border-color: #fff;}
/* Twitch */
.connectedAccountIcon-3_EQqg[src="/assets/ca71e0b8818221eea1deebbaf8dc6518.svg"] ~ div::before {--border-color: #563194;}
/* Twitter */
.connectedAccountIcon-3_EQqg[src="/assets/85cf2b49d2a185c98ec8e383ad5a05d6.svg"] ~ div::before {--border-color: #0099E4;}
/* XBOX */
.connectedAccountIcon-3_EQqg[src="/assets/1fa6585cbb8c0fe21188e26d19fc6609.svg"] ~ div::before {--border-color: #5EC220;}
/* Reddit */
.connectedAccountIcon-3_EQqg[src="/assets/f3224f560c8f5974355596a4f7e9ce19.svg"] ~ div::before {--border-color: #FF4500;}
/* Battle.net */
.connectedAccountIcon-3_EQqg[src="/assets/37f15a06d062bdd0fc252d2b35d0b0bb.svg"] ~ div::before {--border-color: #0099E4;}
/* Steam */
.connectedAccountIcon-3_EQqg[src="/assets/d897626dfa2016ea3ad0af935acb6070.svg"] ~ div::before {--border-color: #000000;}
/* YouTube */
.connectedAccountIcon-3_EQqg[src="/assets/57ee9535485efae7eb923ed4893abb57.svg"] ~ div::before {--border-color: #D9252A;}
/* Facebook */
.connectedAccountIcon-3_EQqg[src="/assets/32045743cb7670855ae726743c949e0c.svg"] ~ div::before {--border-color: #1877F2;}
/* LOL */
.connectedAccountIcon-3_EQqg[src="/assets/94dc6f30a819026fa295d85f1f72b4ab.svg"] ~ div::before {--border-color: #CEA146;}`

**Comment by Poirot12345T** [comment]
I've changed to 2.0 because of the "broken" search bar menu as was mentioned in #12 and it is fixed after changing, but I'm kinda sad that the "Jump to present" bar showing after scrolling too much into the history is Discord-gray (#4c4c4c) and I would expect it to be at least #0a0a0a as is in the server column on the right side of the window. 
And one more thing, would it be hard to change the color under "number-limited voice channel status" to be full black on the left side? I just feel it should be completely black to not be recognisible with the background, but that's maybe only my way of seeing that. 
![image](https://user-images.githubusercontent.com/82270962/146677622-e87d9ea4-844a-4df8-86c1-fba17cd5263a.png)

Debug info:
![image](https://user-images.githubusercontent.com/82270962/146677633-c8a710b7-298b-4bb2-87da-d1684577a535.png)

**Comment by Poirot12345T** [comment]
> > thank you for the feedback, ill also make sure to theme the things i've missed (so if you notice more, let me know)
> > if you notice any other particular plugin that needs an area themed, let me know as well.
> 
> The window to choose "which window to stream" where you can click applications/share screen is also unthemed.

_sorry for spliting into two messages_ The buttons used for webcam/stream/activity looks a little bit too light in my opinion
![image](https://user-images.githubusercontent.com/82270962/146677852-f396abd4-9835-45ee-986f-ffaae36f1f85.png)

**Comment by LuckFire** [comment]
> Stylus style just doesn't work at all, even after refreshing or reopening Firefox.

did you redownload the theme?
