### ISSUE TITLE
[UNTHEMED]: Bar where all the servers are located and folders is not themed

### ISSUE THREAD

**Issue by tripout** [LuckFire/amoled-cord#93]
### Client Mod

Vencord

### Please provide screenshots of the unthemed areas.

The server bar that shows what discords you are in as well as some other minor things. Just started after the last Discord update.

![image](https://github.com/user-attachments/assets/1fd75869-5131-4c35-8488-1ef1805926fa)
![image](https://github.com/user-attachments/assets/5af10ec7-c8ea-42a1-9532-8c46d69d990b)

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by LuckFire** [comment]
You appear to have the new design, either because of eligibility or you have manually enabled it. It is advised to go into experiments and disable it if possible since I do not have plans on support AMOLED-cord with it until it is fully rolled out.

To disable it, go to your user settings, in experiments look for `2024-05_desktop_visual_refresh`, then set it to Not Eligible.

**Comment by tripout** [comment]
Thank you!
